management.endpoints.web.exposure.include: beans,mappings
spring.datasource:
  url: jdbc:postgresql://localhost:5432/jugendhilfe
  username: postgres
  password: postgres
spring:
  jpa:
    properties:
      hibernate:
        default_schema: jugendhilfe


